### PR TITLE
bumping to spring-boot:2.0

### PR DESCRIPTION
**Pull request by tubbynl**
hi, i bumped your example to spring-boot:2.0.0.RELEASE, it needed a newer gradle version and an extra plugin in the buildScript.

the weird thing is that when running the tests in intellij they seem to work; but running the same tests using gradle check doesn't work. it may be Mockito related (the failing tests have that in common)

### CODE REVIEW

**Comment by tubbynl** [comment]
the build is green because i've overridden the mockito.version to 1.10.19 (spring-boot specifies 2.15.0), it is not a nice solution but i don't have a lot of track-record using Mockito, maybe you @damienbeaufils can fill in the blanks here?

**Comment by damienbeaufils** [comment]
Hello @tubbynl,

Thanks for the PR! 

If you run all the tests in IntelliJ, it fails too. I think the issue is related to the way Mockito handle `null` values with `any` matchers in 2.x: if you specify `any(X.class)`, a `null` value won't be matched in Mockito 2.x. I think we should juste replace all the `any(Cipher.class)` and `any(byte[].class)` by `any()`, and it should work fine.

Furthermore, `org.mockito.runners.MockitoJUnitRunner` has been deprecated and we should use `org.mockito.junit.MockitoJUnitRunner` instead.

With these 2 modifications, we could keep transitive Mockito 2.x dependency. :)

**Comment by tubbynl** [comment]
cool, now the gradle build is also green

**Comment by tubbynl** [comment]
food for thought; (and not really this issue) if the algoritm is changed to DESede instead of AES it works out of the box most JVM's, using AES forces the user to first install those JCE thingies and stuff

it would also omit the need to use Mockito on some of the tests, example-wise it more clean, perhaps the default in the implementation could still be AES (for when people copy-paste) but for the tests DESede is used

**Comment by damienbeaufils** [comment]
Thanks for the idea of using DESede instead of AES. I don't have the time to work on it right now, but if you want to make a PR about that, feel free ;-)

**Pull request merged**
